export const books = [
  {
    id: 1,
    title: 'Human Hack',
    author: 'Alice Johnson',
    pages: 265,
    desc: '',
  },
  {
    id: 2,
    title: 'The Hax',
    author: 'George Bush',
    pages: 343,
    desc: '',
  },
  {
    id: 3,
    title: 'The Test',
    author: 'Paul Screw',
    pages: 190,
    desc: '',
  },
  {
    id: 4,
    title: 'The Gorge',
    author: 'Allen Davidson',
    pages: 590,
    desc: '',
  },
  {
    id: 5,
    title: 'The Water in Paris',
    author: 'Georgia Bushsin',
    pages: 456,
    desc: '',
  },
  {
    id: 6,
    title: 'The Lion',
    author: 'Forrest Sure',
    pages: 1190,
    desc: '',
  },
  {
    id: 7,
    title: ' Guardian',
    author: 'Steve Ball',
    pages: 657,
    desc: '',
  },
  {
    id: 8,
    title: 'Free Throw',
    author: 'Ryan Joe',
    pages: 1256,
    desc: '',
  },
];
